import type { Metadata } from "next";
import "./globals.css";
import SignoutButton from "@/components/SignoutButtton";

export const metadata: Metadata = {
  title: "4537 Term Project",
  description: "Generated by a group of students for 4537.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SignoutButton/>
        {children}
      </body>
    </html>
  );
}
